sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
  - pypy3.5
install:
 - pip install -U pip
 - pip install -U wheel setuptools
 - pip install -r requirements.txt
 - pip list
 - python --version
script:
 - python setup.py test
